name = "PCIVEPMBiome2024"
uuid = "0007ff0d-c293-43f4-ad92-44c710bdace4"
authors = ["Guilherme Fabur Bottino <gfahurbottino@gmail.com> and contributors"]
version = "1.0.0-DEV"

[deps]
Arrow = "69666777-d1a9-59fb-9406-91d4454c9d45"
BiobakeryUtils = "fa5322f5-bd84-5069-834a-abf3230fb8f8"
Bootstrap = "e28b5b4c-05e8-5b66-bc03-6f0c0a0a06e0"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
CategoricalArrays = "324d7699-5711-5eae-9e2f-1d82baa6b597"
Chain = "8be319e6-bccf-4806-a6f7-6fae938471bc"
Clustering = "aaaa29a8-35af-508c-8bc3-b662a17a0fe5"
CodecZlib = "944b1d66-785c-5afd-91f1-9de20f533193"
ColorSchemes = "35d6a980-a343-548e-a6ea-1d62b119f2f4"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DecisionTree = "7806a523-6efd-50cb-b5f6-3fa6f1930dbb"
Dictionaries = "85a47980-9c8c-11e8-2b9f-f7ca1fa99fb4"
Distances = "b4f34e82-e78d-54a5-968a-f98e89d6e8f7"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Diversity = "d3d5718d-52de-57ab-b67a-eca7fd6175a4"
FeatureSetEnrichments = "86280b8e-e847-4559-a126-2dcda5c07d84"
GLM = "38e38edf-8417-5370-95a0-9cbb8c7f171a"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
HypothesisTests = "09f84164-cd44-5f33-b23f-e6b0d136a0d5"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
Leap = "e19c48ec-5b69-490e-8125-dadf8a0b819c"
Microbiome = "3bd8f0ae-a0f2-5238-a5af-e1b399a4940c"
MultipleTesting = "f8716d33-7c4a-5097-896f-ce0ecbd3ef6b"
MultivariateStats = "6f286f6a-111f-5878-ab1e-185364afe411"
PrettyTables = "08abe8d2-0d0c-5749-adfa-8a2ac140af0d"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
StatsModels = "3eaba693-59b7-5ba5-a881-562e759f1c8d"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"
ThreadsX = "ac1d9e8a-700a-412c-b207-f0111f4b6c0d"

[compat]
Arrow = "2.8.0"
Bootstrap = "2.4.0"
CairoMakie = "0.15"
ProgressMeter = "1.10.4"
StatsModels = "0.6.33"
Tables = "1.12.1"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
